### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by mabihan** [eclipse/risev2g#1]
I need help to get this running. Could someone explain which are the steps to successfully run the server then the client ?

**What I have done so far**
- I created three Eclipse projects (RISE V2G-EVCC, RISE V2G-SECC, RISE V2G-Shared).
- I transferred of each **/org** repertory from the GitHub archive to the **/src** repertory in the Eclipse projects
- I downloaded log4j and Xerces, and add the jar to the build path of the three projects.
- I add the RISE V2G-Shared project to the build path of the two others projects (RISE V2G-EVCC and RISE V2G-SECC)

At this point, I have no warning from Eclipse. 
When I run the SECC application, I chose _Java Application_ and then _ConsoleAppenderAnsiMessageMain_, but I get an exception : `java.lang.ClassNotFoundException: org.slf4j.Logger`

The log4j jar files are added to the build path, and there is no warning on the import that the file **MiscUtils.java** does :
`import org.apache.logging.log4j.Logger;`
`import org.apache.logging.log4j.LogManager;`

Thank you for your help.

**Comment by MarcMueltin** [comment]
Hi Jean, 

welcome to the RISE V2G project. :)
The existing code repository is actually a [Maven repository](https://maven.apache.org) which is intended to help you get started more easily without the hassle to organize the structure, configure building paths and downloading libraries. So if you just import an existing Maven project in your IDE (such as Eclipse) the steps needed should automatically be done right for you. 
I will probably provide a short "Maven getting started" for those not familiar with it.

But now back to your specific problem:
You should start the SECC application by executing the class StartSECC.java (Run as > Java Application) in the package org.eclipse.risev2g.secc.main (as stated in the [getting started guide](https://wiki.eclipse.org/RISE_V2G)). I am not sure what you mean with the ConsoleAppenderAnsiMessageMain though. 

Did this solve your problem?

**Comment by mabihan** [comment]
Yes, thanks a lot!
 As you said, I am not familiar with Maven so I tried to import the project as a normal one. 
Now, I successfully ran a V2G session on the same machine (An OpenSUSE laptop on which I had to disabled the firewall). If I want to run a session between two machine on the same network, I guess I have to modify the "NetworkInterface" field in the *.properties files. 

Should I name both the same with the interface of the server machine ? 

In my case I have two laptop (OpenSUSE and Windows) and the first session ran successfully on the OpenSUSE using the Ethernet interface (`enp0s25`) for both entities. But now I want to run it on two separate computers on the same network and my first attempts were unfruitful.  Any advice ?

**Comment by MarcMueltin** [comment]
Hi Jean, 

you might have to try out your various network interfaces and adjust the setting in the respective .properties file. So I have e.g. 'lo0' (the loopback device) set for the NetworkInterface property both in SECCConfig.properties and EVCCConfig.properties file - for testing purposes where I run SECC and EVCC both on the same machine. 

This will not work when running the SECC on one machine and the EVCC on another machine. I usually use 'en0' or 'en1' (on my Mac) as network device for SECC and/or EVCC. You can check your available network interfaces on a Unix/Linux machine by running the command 'ifconfig' in the terminal window (I think it's 'ipconfig' on a Windows machine). 

Got it working?

**Comment by mabihan** [comment]
Hi,

No, and I did not even get it working on the same windows machine : 
The program doesn't accept any of the interface name I provided. I tried `"Ethernet-Adapter"`, 
`"LAN-Verbindung"`, `"Intel(R) 82579LM Gigabit Network Connection"` but each one failed.

Here is what I get when I look at the properties of my Ethernet connection
![2015-06-17 13_32_57-networkinterfacesview](https://cloud.githubusercontent.com/assets/7303757/8205939/67668084-14f5-11e5-9a91-6971c1b7c506.png)

Thank your for your time.

**Comment by MarcMueltin** [comment]
Hmm, it seems that those short names like "en0" or "eth0" are not listed on a Windows machine when you type "ipconfig" in a console window. I am not working on a Windows machine, but I came across [this article](http://www.codedisqus.com/fmmJxWUkXU/what-would-be-the-lo-interface-equivalent-on-windows.html). What happens if you try "localhost" or "loopback" as values in the properties files?

**Comment by MarcMueltin** [comment]
For further readers:
The issue has been solved by Jean within the Gitter chat. A modification of the class MiscUtils.java (in the org.eclipse.risev2g.shared.utils) will be made available to make the provision of a network interface platform independent. This means that not a string should be provided (such as "lo0", "eth3", etc), but rather a numeric index value. The value must correspond to the network interface holding the link-local IPv6 address. Thanks for your effort, Jean. :+1:
