### ISSUE TITLE
SignedInfo tag namespace issue

### ISSUE THREAD

**Issue by hanyu-natsu** [eclipse/risev2g#3]
I encountered this issue while verifying the signature contained in _AuthorizationReq_ sent by EVCC.

The verification failed due to the fact that the **<SignedInfo>** element which is used to be digested uses "**urn:iso:15118:2:2013:MsgBody**" as its namespace. But according to the XML digital signature schema, this should be "**http://www.w3.org/2000/09/xmldsig#**".

This problem comes from the method `public static JAXBElement getJaxbElement(Object messageOrField)` in `org.eclipse.risev2g.shared.utils.MiscUtils.java`.

Actually the namespace is hard coded with "**urn:iso:15118:2:2013:MsgBody**" regardless the type of the message object. This is also why the SECC in risev2g can verify the signature.

I think this could be solved by either using the `ObjectFactory` or by analyzing the object class name. For the moment I just check if the object is a "SignedInfoType" and if it is, the xmlsig namespace will be used.

**Comment by MarcMueltin** [comment]
Hi lihanyu23, 

thanks a lot for your hint! I did not have any issues with this code on any testival I have been so far. But as it seems, my testpartner did not address this issue either.

So I followed your suggestion with checking for the SignedInfoType. Could you please pull the current update and test it with your implementation?
See https://github.com/eclipse/risev2g/commit/72d0327a725e6a4060b78e0887d0fddfe449e2a4

**Comment by hanyu-natsu** [comment]
Thank you Marc for your fix. I have tested it with my implementation, it works well.

It seems that till now all things need to be signed have the "MsgBody" namespace except the SignedInfo. My concern is that if one day something having another namespace should be signed, the fix will not cover that.

**Comment by MarcMueltin** [comment]
Taking for example the AuthorizationReq message, you can see that in total 4 namespaces are used:

xmlns:ns6="urn:iso:15118:2:2013:MsgDef"
xmlns:ns5="http://www.w3.org/2000/09/xmldsig#"
xmlns:ns7="urn:iso:15118:2:2013:MsgBody"
xmlns:ns3="urn:iso:15118:2:2013:MsgHeader"

So we need more than just the MsgBody namespace, but other schemas inherit from MsgBody as I remember.

See the following XML message of the AuthorizationReq which you can better view in a code beautifier like http://codebeautify.org/xmlviewer:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns6:V2G_Message xmlns:ns6="urn:iso:15118:2:2013:MsgDef" xmlns:ns5="http://www.w3.org/2000/09/xmldsig#" xmlns:ns7="urn:iso:15118:2:2013:MsgBody" xmlns:ns2="urn:iso:15118:2:2010:AppProtocol" xmlns:ns4="urn:iso:15118:2:2013:MsgDataTypes" xmlns:ns3="urn:iso:15118:2:2013:MsgHeader"><ns6:Header><ns3:SessionID>419A9DD23E3930E2</ns3:SessionID><ns5:Signature><ns5:SignedInfo><ns5:CanonicalizationMethod Algorithm="http://www.w3.org/TR/canonical-exi"/><ns5:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"/><ns5:Reference Id="authorizationReq" URI="#authorizationReq"><ns5:Transforms><ns5:Transform Algorithm="http://www.w3.org/TR/canonical-exi"/></ns5:Transforms><ns5:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ns5:DigestValue>RR+/JQv74CRTq2RooivKvuS100CU9PJNjz+woSG2rks=</ns5:DigestValue></ns5:Reference></ns5:SignedInfo><ns5:SignatureValue>MEUCIHSECNLPPJdWBioB5tbgbPZGpmaESjqHVUMYYRRUosMUAiEAhfLKlmDTX7+8tLD64+hBjHmSPAMCsPt4ImGO8ZUr7no=</ns5:SignatureValue></ns5:Signature></ns6:Header><ns6:Body><ns7:AuthorizationReq ns7:Id="authorizationReq"><ns7:GenChallenge>fPLn7fjonDB/mTEQDScw1g==</ns7:GenChallenge></ns7:AuthorizationReq></ns6:Body></ns6:V2G_Message>
```

By the way, I removed the hardcoded namespace (never a good idea to hardcode sth. ;) ) and instead introduced two new global values
- V2G_CI_MSG_BODY_NAMESPACE("urn:iso:15118:2:2013:MsgBody")
- V2G_CI_XMLDSIG_NAMESPACE("http://www.w3.org/2000/09/xmldsig#)

in shared.enumerations.GlobalValues.java next to the already existing
- V2G_CI_MSG_DEF_NAMESPACE("urn:iso:15118:2:2013:MsgDef")

If new namespaces arise (for example for the new upcoming edition 2 of ISO 15118-2), then the GlobalValues.java is the place to provide them throughout the project.

Furthermore, I extended the marshaller code in the shared.exiCodec.ExiCodec.java to show the XML representation of each message. Might be helpful for debugging purposes.
See https://github.com/eclipse/risev2g/commit/9ee2d21472ce86a2ad58cb19944a61f5cd0c54b7

**Comment by hanyu-natsu** [comment]
It is true that what is signed in the current version of ISO 15118 has always  "urn:iso:15118:2:2013:MsgBody" as its namespace.

But for example, the "ContractSignatureCertChain" signed in the "CertificateUpdateRes", it uses "urn:iso:15118:2:2013:MsgBody" because it belongs to "CertificateUpdateRes" defined in the body schema. However, imagine the case where we shall sign the "SubCertificates", then the namespace used will be "urn:iso:15118:2:2013:MsgDataTypes", not the body one.

Hope that I was clear on this point.
