### ISSUE TITLE
generateCertificates.sh fails due to many missing folders

### ISSUE THREAD

**Issue by kartben** [eclipse/risev2g#5]
It does not look like the repo actually includes the different certificates and keystores needed (and mentioned in generateCertificates.sh [1]).
generateCertificates.sh fails unless one creates manually `certs/`, `csrs/`, `keystores/` and `privateKeys/` folders. I guess the script should be updated to either create those folders if they don't exist already, or the keys, certificates, etc should be committed, but may be that's not desired as they seem to be gitignore'd today.

[1] "Previously created certificates should have been provided with the respective release of the RISE V2G project for testing purposes"

**Comment by MarcMueltin** [comment]
Issue has been resolved with release tagged as [v.0.9.6](https://github.com/eclipse/risev2g/releases/tag/v.0.9.6).
The script generateCertificates.sh now checks if the necessary directories are already existing and creates them, if not already there.
